apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-project
  namespace: argocd
spec:
  description: ArgoCD Project to deploy wil-playground app
  sourceRepos:
  - "https://github.com/Junya42/*"
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
