Vagrant.configure(2) do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.box_url = "debian/bookworm64"

    config.vm.synced_folder ".", "/vagrant_shared"

    config.vm.define "cmaroufS" do |config|
      config.vm.hostname = "cmaroufS"
      config.vm.network "private_network", ip: "192.168.56.110"
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", "cmaroufS", "--memory", 4096, "--cpus", 1]
      end
      config.vm.provision "k3s shell script", type: "shell",
        path: "./scripts/k3s_server.sh"
    end
end
