Vagrant.configure(2) do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.box_url = "debian/bookworm64"

    config.vm.define "cmaroufS" do |config|
      config.vm.hostname = "cmaroufS"
      config.vm.network "private_network", ip: "192.168.56.110"
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", "cmaroufS", "--memory", 512, "--cpus", 1]
      end
      config.vm.provision "k3s shell script", type: "shell",
        path: "k3s_install.sh"
    end

    config.vm.define "cmaroufSW" do |config|
      config.vm.hostname = "cmaroufSW"
      config.vm.network "private_network", ip: "192.168.56.111"
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", "cmaroufSW", "--memory", 512, "--cpus", 1]
      end
      config.vm.provision "k3s shell script", type: "shell",
        path: "k3s_install.sh"
    end


end
